// examples/react-quickstart/app/page.tsx
"use client";

import { SignIn, UserButton, useAuth } from "@hellojohn/react";

export default function Page() {
  const { isAuthenticated, user } = useAuth();

  return (
    <main style={{ padding: 24 }}>
      <UserButton />
      {isAuthenticated ? <p>Welcome, {user?.email}</p> : <SignIn />}
    </main>
  );
}

// examples/vue-quickstart/src/App.vue
<script setup lang="ts">
import { HjSignIn, HjUserButton, useAuth } from "@hellojohn/vue";

const { isAuthenticated, user } = useAuth();
</script>

<template>
  <main style="padding: 2rem">
    <HjUserButton />
    <HjSignIn v-if="!isAuthenticated" />
    <p v-else>Welcome, {{ user?.email }}</p>
  </main>
</template>
